// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArT5Wdakh1mXAi8ygFaK7yaYe4qupec7Q',
    appId: '1:676828935630:web:c304e79fe85355b605a79f',
    messagingSenderId: '676828935630',
    projectId: 'pard-app-project',
    authDomain: 'pard-app-project.firebaseapp.com',
    storageBucket: 'pard-app-project.appspot.com',
    measurementId: 'G-KZP2WRTZQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuSzECIeL4af0rwUdUC0Y4xH6bVLBR60',
    appId: '1:676828935630:android:cd84d5445726a3f205a79f',
    messagingSenderId: '676828935630',
    projectId: 'pard-app-project',
    storageBucket: 'pard-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnLAm1IPNOSfUAiG9h_bIc2LAI1bYy0rY',
    appId: '1:676828935630:ios:2bddeeed6f3f25d605a79f',
    messagingSenderId: '676828935630',
    projectId: 'pard-app-project',
    storageBucket: 'pard-app-project.appspot.com',
    iosClientId: '676828935630-o0m4qfq5i5f0j5mjo3uvsel9099ngg0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnLAm1IPNOSfUAiG9h_bIc2LAI1bYy0rY',
    appId: '1:676828935630:ios:f3629abcfb32cc7705a79f',
    messagingSenderId: '676828935630',
    projectId: 'pard-app-project',
    storageBucket: 'pard-app-project.appspot.com',
    iosClientId: '676828935630-sfm0a65oqnents0no6ecb9c9bvkak2kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pardApp.RunnerTests',
  );
}
